# Generated by Django 5.1 on 2024-08-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('condition', models.CharField(max_length=100)),
                ('wind_speed', models.FloatField()),
                ('pressure', models.FloatField()),
                ('visibility', models.FloatField()),
                ('uv_index', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
